app_env: test
user:
group:
http_port: 9080
https_port: 9081
analytics:
  timezone: America/Denver
static_site:
  port: 13013
  listen:
    port: 13013
nginx:
  # We default the number of workers to the number of CPU cores, but keep this
  # hard-coded for test purposes so we have a more stable baseline and ensure
  # our tests always run with multiple workers.
  workers: 2
  # Disable log output buffering for immediate output in tests.
  access_log_options:
  # Increase error log verbosity in tests.
  error_log_level: notice
trafficserver:
  port: 13009
envoy:
  port: 13000
  listen:
    port: 13000
  admin:
    port: 13001
    listen:
      port: 13001
  http_proxy:
    port: 13002
    listen:
      port: 13002
  smtp_proxy:
    port: 13003
    listen:
      port: 13003
  # Flush logs more frequently in test.
  cli_args: "--file-flush-interval-msec 500"
envoy_control_plane:
  port: 13007
  listen:
    port: 13007
  metrics_listen:
    port: 13008
api_server:
  port: 13010
  listen:
    port: 13010
web:
  port: 13012
  listen:
    port: 13012
  admin:
    auth_strategies:
      facebook:
        client_id: test_fake_id
        client_secret: test_fake_secret
      github:
        client_id: test_fake_id
        client_secret: test_fake_secret
      gitlab:
        client_id: test_fake_id
        client_secret: test_fake_secret
      google:
        client_id: test_fake_id
        client_secret: test_fake_secret
      ldap:
        options:
          host: 127.0.0.1
          port: 389
          method: plain
          base: dc=example,dc=com
          uid: sAMAccountName
  mailer:
    smtp_settings:
      address: 127.0.0.1
      port: 13102
  contact_form_email: default-test-contact-email@example.com
  analytics_v0_summary_start_time: "2013-07-01T00:00:00.000-06:00"
  analytics_v0_summary_end_time: "2013-08-31T23:59:59.999-06:00"
router:
  trusted_proxies:
    - 192.168.12.0/23
    - 10.10.10.10
  active_config:
    # Force the local cache to be refreshed on every request, instead of in the
    # background. The background behavior is probably fine in production, where
    # it's fine if things are eventually consistent across the workers after
    # 1-2 seconds, but to make testing easier, force immediate refreshes in the
    # test environment.
    refresh_local_cache_interval: 0
fluent_bit:
  port: 13014
  service:
    flush: 0.1
geoip:
  db_update_frequency: false
postgresql:
  database: api_umbrella_test
  password: dev_password
  migrations:
    password: dev_password
opensearch:
  index_name_prefix: "api-umbrella-test"
  template:
    index:
      # In the test environment, disable replicas, reduce shards, and
      # increasing refresh interval to speed things up.
      refresh_interval: 50ms
      number_of_shards: 1
      number_of_replicas: 0
unbound:
  port: 13100
  control_port: 13101
glauth:
  port: 13104
default_api_backend_settings:
  require_https: optional
_test_config:
  default_null_override_hash:
    foo: bar
  default_null_override_string: foobar
  default_empty_hash_override_hash:
    baz: qux
apis:
  - id: 00000000-0000-0000-0000-100000000000
    name: default-test-api-backend
    backend_protocol: http
    balance_algorithm: least_conn
    frontend_host: 127.0.0.1
    backend_host: 127.0.0.1
    servers:
      - id: 00000000-0000-0000-0000-200000000000
        host: 127.0.0.1
        port: 9444
    url_matches:
      - id: 00000000-0000-0000-0000-300000000000
        frontend_prefix: /api/
        backend_prefix: /
